import React, { useState } from 'react';

function App() {
  const [pdfFile, setPdfFile] = useState(null);
  const [summary, setSummary] = useState('');

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file && file.type === 'application/pdf') {
      setPdfFile(file);
    } else {
      alert('Please select a PDF file.');
    }
  };

  const handleSummarize = () => {
    if (pdfFile) {
      // Call your AI summarization service here
      // Replace this placeholder code with your actual implementation
      // This is just a placeholder for demonstration purposes
      setSummary('This is a placeholder summary generated by AI.');
    } else {
      alert('Please upload a PDF file first.');
    }
  };

  return (
    <div className="App">
      <h1>PDF Summarizer</h1>
      <input type="file" accept="application/pdf" onChange={handleFileChange} />
      <button onClick={handleSummarize}>Summarize PDF</button>
      {summary && (
        <div>
          <h2>Summary</h2>
          <p>{summary}</p>
        </div>
      )}
    </div>
  );
}

export default App;
